
% --------------------------------------------------------- Initialization

function varargout = QuailKit_export(varargin)
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
    'gui_Singleton',  gui_Singleton, ...
    'gui_OpeningFcn', @QuailKit_export_OpeningFcn, ...
    'gui_OutputFcn',  @QuailKit_export_OutputFcn, ...
    'gui_LayoutFcn',  @QuailKit_export_LayoutFcn, ...
    'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end
if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end

function QuailKit_export_OpeningFcn(hObject, eventdata, handles, varargin)
addpath(genpath(pwd));
handles.Path.Recordings='../../Quail Call - Recordings/';
handles.Path.Spectrograms='../../Quail Call - Shared/data/spectrograms/';
handles.Path.Results='../../Quail Call - Shared/results/';
handles=SetValues(handles);
handles=SetAxis(handles,true);
handles=SetGraphics_All(handles);
handles=SetToolbar(handles);
handles=SetPlay(handles);
handles=Set12(handles,true);
handles=Set34(handles);
handles.Graphics.Credits=Credits(...
    handles.Graphics.Watermark,...
    handles.Graphics.Color,true);
handles.Graphics.Watermark=HT_Transition(...
    handles.Graphics.Watermark,{'YLim'},...
    [1-handles.Graphics.Watermark.Position(4),0],...
    handles.UserData.Frames,handles);
handles=Wait(handles,'off');
handles.Data.j=1;
handles=SetLayout(handles,handles.UserData.Frames);
handles.output = hObject;
guidata(hObject,handles);

function varargout = QuailKit_export_OutputFcn(hObject, eventdata, handles)
varargout{1} = handles.output;

% ------------------------------------------------------- Figure Callbacks

function Fig_SizeChangedFcn(hObject, eventdata, handles)
handles=SetLayout(handles,2);
guidata(handles.Fig,handles);

function Fig_KeyReleaseFcn(hObject, eventdata, handles)
handles = HT_Compute(handles);
handles=SetView(handles,false);
guidata(handles.Fig,handles);

function Fig_KeyPressFcn(hObject, eventdata, handles)
switch eventdata.Key
    case 'rightarrow'
        handles.Data.j=min(handles.Data.j+1,length(handles.Data.Bins)-1);
    case 'leftarrow'
        handles.Data.j=max(1,handles.Data.j-1);
    case 'downarrow'
        handles.Data.j=min(handles.Data.j+10,length(handles.Data.Bins)-1);
    case 'uparrow'
        handles.Data.j=max(1,handles.Data.j-10);
end
if ismember(eventdata.Key,{'rightarrow','leftarrow','downarrow','uparrow'})
    set(handles.Graphics.Axis(3).Children,...
        'Visible','off');
    set(handles.Graphics.Axis(2).Children,...
        'Visible','off');
    handles.Graphics.Patch(1).XData=handles.Data.TS.Time(...
        [handles.Data.Edges(handles.Data.j),...
        handles.Data.Edges(handles.Data.j+1),...
        handles.Data.Edges(handles.Data.j+1),...
        handles.Data.Edges(handles.Data.j)]);
    set(handles.Graphics.Axis(2),...
        'XLim',handles.Graphics.Patch(1).XData(1:2));
    guidata(hObject,handles);
end

% ---------------------------------------------------- GroupPlay Callbacks

function Clear_Callback(hObject, eventdata, handles)
handles.Data.j=1;
handles=HT_Compute(handles);
handles=SetView(handles,false);
guidata(hObject,handles);

function Reset_Callback(hObject, eventdata, handles)
handles=SetAxis(handles,initialize);
handles=Wait(handles,'off');
handles.Data.j=1;
handles=SetLayout(handles,handles.UserData.Frames);
handles=HT_DataAccess(handles,'read');
handles=HT_Compute(handles);
handles=SetView(handles,false);
guidata(hObject,handles);

function Skip_Callback(hObject, eventdata, handles)
hObject.UserData=1;
if handles.Data.j<length(handles.Data.Bins)-1
    handles.Data.j=handles.Data.j+1;
else
    handles.Data.j=1;
end
handles=HT_Compute(handles);
handles=SetView(handles,false);
guidata(hObject,handles);

function Next_Callback(hObject, eventdata, handles)
handles.Data.j=1;
handles.One_Pop.Value=handles.One_Pop.Value+1;
handles=SetGraphics_All(handles);
handles=SetToolbar(handles);
handles=SetPlay(handles);
handles=Set12(handles,false);
handles=Set34(handles);
handles=Wait(handles,'off');
handles=SetLayout(handles);
handles=HT_DataAccess(handles,'read');
guidata(hObject,handles);

function PlayMode_Callback(hObject, eventdata, handles)
handles.PlayMode.UserData=rem(handles.PlayMode.UserData+1,4);
handles=SetGraphics_All(handles);
handles=SetToolbar(handles);
handles=SetPlay(handles);
handles=Set12(handles,false);
handles=Set34(handles);
handles=Wait(handles,'off');
handles=SetLayout(handles);
guidata(hObject,handles);

function Mode_Callback(hObject, eventdata, handles)
handles.Mode.UserData=rem(handles.Mode.UserData+1,3);
handles=SetGraphics_All(handles);
handles=SetToolbar(handles);
handles=SetPlay(handles);
handles=Set12(handles,false);
handles=Set34(handles);
handles=Wait(handles,'off');
handles=SetLayout(handles);
guidata(hObject,handles);

function Debug_Callback(hObject, eventdata, handles)
handles.Debug.UserData=rem(handles.Debug.UserData+1,2);
handles=SetGraphics_All(handles);
handles=SetToolbar(handles);
handles=SetPlay(handles);
handles=Set12(handles,false);
handles=Set34(handles);
handles=Wait(handles,'off');
handles=SetLayout(handles);
guidata(hObject,handles);

function Previous_Callback(hObject, eventdata, handles)
if handles.One_Pop.Value>2
    handles.One_Pop.Value=handles.One_Pop.Value-1;
    handles=SetGraphics_All(handles);
    handles=SetToolbar(handles);
    handles=SetPlay(handles);
    handles=Set12(handles,false);
    handles=Set34(handles);
    handles=Wait(handles,'off');
    handles=SetLayout(handles);
    handles.Data.j=1;
    handles=HT_DataAccess(handles,'read');
    guidata(hObject,handles);    
end

function Back_Callback(hObject, eventdata, handles)
hObject.UserData=1;
if handles.Data.j>1
    handles.Data.j=handles.Data.j-1;
else
    handles.Data.j=length(handles.Data.Bins);
end
handles=HT_Compute(handles);
handles=SetView(handles,false);
guidata(hObject,handles);

function QueueMode_Callback(hObject, eventdata, handles)
handles.QueueMode.UserData=rem(handles.QueueMode.UserData+1,2);
handles=SetGraphics_All(handles);
handles=SetToolbar(handles);
handles=SetPlay(handles);
handles=Set12(handles,false);
handles=Set34(handles);
handles=Wait(handles,'off');
handles=SetLayout(handles);
guidata(hObject,handles);

function Play_Callback(hObject, eventdata, handles)
if handles.Data.Audio.isplaying
    handles.Data.Audio.pause;
elseif hObject.UserData==1
    hObject.UserData=0;
else
    hObject.UserData=1;
    hObject.CData=handles.icons.Pause;
    flag=false;
    while hObject.UserData==1
        if handles.PlayMode.UserData==0
            handles.Skip.UserData=0;
            handles.Back.UserData=0;
            hObject.UserData=0;
        else
            if flag
                if handles.Data.j<length(handles.Data.Edges)-2
                    handles.Data.j=handles.Data.j+1;
                    if handles.PlayMode.UserData==1
                        hObject.UserData=0;
                    end
                elseif handles.PlayMode.UserData==3
                    handles.Data.j=1;
                elseif handles.QueueMode.Value==1
                    Next_Callback(handles.Next, eventdata, handles);
                    handles.Skip.UserData=0;
                end
                handles=HT_Compute(handles);
                handles=SetView(handles,false);
            end
        end
        if strcmp(handles.Sound.State,'on')
            handles.Data.Audio.resume;
            set(handles.Graphics.Line(1:2),'Visible','on');
            waitfor(handles.Data.Audio,'Running','off');
            set(handles.Graphics.Line(1:2),'Visible','off');
        end
        flag=true;
    end
end
hObject.UserData=0;
hObject.CData=handles.icons.Play;
guidata(hObject,handles);

% ----------------------------------------------------- Group12 Callbacks

function One_Pop_Callback(hObject, eventdata, handles)
handles=Wait(handles,'on');
handles=Set12(handles,false);
handles.One_List.Value=1;
handles=HT_DataAccess(handles,'read');
handles=HT_Compute(handles);
handles=SetView(handles,false);
handles=SetGraphics_All(handles);
handles=SetToolbar(handles);
handles=SetPlay(handles);
handles=Set12(handles,false);
handles=Set34(handles);
handles=Wait(handles,'off');
guidata(hObject,handles);

function One_List_Callback(hObject, eventdata, handles)
handles=Wait(handles,'on');
handles=Set12(handles,false);
handles=HT_DataAccess(handles,'prepare');
handles=SetGraphics_All(handles);
handles=SetToolbar(handles);
handles=SetPlay(handles);
handles=Set12(handles,false);
handles=Set34(handles);
handles=Wait(handles,'off');
guidata(hObject,handles);

function Two_Pop_Callback(hObject, eventdata, handles)
handles.Two_List.Value = 1;
handles=Set12(handles,false);
guidata(hObject,handles);

function Two_List_Callback(hObject, eventdata, handles)
value=handles.Two_Pop.UserData{handles.Two_Pop.Value,2}{hObject.Value,2};
switch class(value)
    case 'logical'
        handles.Two_Slide.Value=double(value);
    case 'double'
        handles.Two_Slide.Value=value;
end
handles=Set12(handles,false);
guidata(hObject,handles);

function Two_Slide_Callback(hObject, eventdata, handles)
handles=Wait(handles,'on');
switch hObject.Style
    case 'slider'
        temp=hObject.Value;
    case 'checkbox'
        temp=logical(hObject.Value);
end
handles.Two_Pop.UserData{handles.Two_Pop.Value,2}...
    {handles.Two_List.Value,2}=temp;
handles=Set12(handles,false);
handles=SetLayout(handles,handles.UserData.Frames);
handles=HT_DataAccess(handles,'read');
handles=HT_Compute(handles);
handles=SetView(handles,false);
handles=SetGraphics_All(handles);
handles=SetToolbar(handles);
handles=SetPlay(handles);
handles=Set12(handles,false);
handles=Set34(handles);
handles=Wait(handles,'off');
guidata(hObject,handles);

% ------------------------------------------------------ Group45 Callbacks

function Four_Pop_Callback(hObject, eventdata, handles)
handles = Set34(handles);
handles=HT_Compute(handles);
handles=SetView(handles,false);
handles=SetLayout(handles);
guidata(hObject,handles);

function Four_List_Callback(hObject, eventdata, handles)
handles = Set34(handles);
value=hObject.UserData{handles.Four_Pop.Value}{2,hObject.Value};
switch class(value)
    case 'logical'
        handles.Four_Slide.Value=double(value);
    case 'double'
        handles.Four_Slide.Value=value;
end
guidata(hObject,handles);

function Four_Slide_Callback(hObject, eventdata, handles)
switch hObject.Style
    case 'slider'
        temp=hObject.Value;
    case 'checkbox'
        temp=logical(hObject.Value);
end
handles.Four_List.UserData{handles.Four_Pop.Value}...
    {2,handles.Four_List.Value}=temp;
handles = Set34(handles);
handles=SetLayout(handles,handles.UserData.Frames);
handles=HT_Compute(handles);
handles=SetView(handles,false);
guidata(hObject,handles);

function Five_Pop_Callback(hObject, eventdata, handles)
handles = Set34(handles);
handles=SetLayout(handles,handles.UserData.Frames);
handles=HT_Compute(handles);
handles=SetView(handles,false);
guidata(hObject,handles);

function Five_List_Callback(hObject, eventdata, handles)
handles = Set34(handles);
handles=SetLayout(handles,handles.UserData.Frames);
value=hObject.UserData{hObject.Value,2};
switch class(value)
    case 'logical'
        handles.Five_Slide.Value=double(value);
    case 'double'
        handles.Five_Slide.Value=value;
end
guidata(hObject,handles);

function Five_Slide_Callback(hObject, eventdata, handles)
switch hObject.Style
    case 'slider'
        temp=hObject.Value;
    case 'checkbox'
        temp=logical(hObject.Value);
end
handles.Five_List.UserData{handles.Five_List.Value,2}=temp;
handles = Set34(handles);
handles=SetLayout(handles);
handles=HT_Compute(handles);
handles=SetView(handles,false);
guidata(hObject,handles);

% ------------------------------------------------------ Toolbar Callbacks

function HT_OffCallback(hObject, eventdata, handles)
handles=Wait(handles,'on');
handles=SetGraphics_All(handles);
handles=SetToolbar(handles);
handles=SetPlay(handles);
handles=Set12(handles,false);
handles=Set34(handles);
handles=Wait(handles,'off');
guidata(hObject,handles);

function HT_OnCallback(hObject, eventdata, handles)
handles=Wait(handles,'on');
handles.Graphics.Watermark=...
    HT_Transition(handles.Graphics.Watermark,{'YLim'},...
    [1-handles.Graphics.Watermark.Position(4),0],...
    handles.UserData.Frames,handles);
set(handles.HT,'Enable','on');
guidata(hObject,handles);

function Zoom_ClickedCallback(hObject, eventdata, handles)
hObject=Feedback(hObject);
drawnow
handles.UserData.ZoomMode=rem(handles.UserData.ZoomMode+1,4);
SetView(handles,handles.UserData.Frames);
hObject=Feedback(hObject);
guidata(hObject,handles);

function Theme_ClickedCallback(hObject, eventdata, handles)
hObject=Feedback(hObject);
drawnow
hObject.UserData=max(1,rem(hObject.UserData+1,14));
handles=SetGraphics_All(handles);
handles=SetLayout(handles,handles.UserData.Frames);
handles=SetToolbar(handles);
guidata(hObject,handles);

function Display_ClickedCallback(hObject, eventdata, handles)
hObject=Feedback(hObject);
drawnow
handles.DisplayMode=rem(handles.DisplayMode+1,4);
handles=SetLayout(handles,handles.UserData.Frames);
hObject=Feedback(hObject);
guidata(hObject,handles);

function InvertColors_ClickedCallback(hObject, eventdata, handles)
handles=SetGraphics_All(handles);
handles=SetLayout(handles,handles.UserData.Frames);
handles=SetToolbar(handles);
guidata(hObject,handles);

function Animation_ClickedCallback(hObject, eventdata, handles)
handles=SetToolbar(handles);
guidata(hObject,handles);

function Sound_ClickedCallback(hObject, eventdata, handles)
handles=SetToolbar(handles);
guidata(hObject,handles);

function Save_ClickedCallback(hObject, eventdata, handles)
hObject=Feedback(hObject);
pause(0.5);
Feedback(hObject);
guidata(hObject,handles);

function Capture_OnCallback(hObject, eventdata, handles)
handles.UserData.HiddenFig=...
    figure('Visible','off','Position',[0,0,1008,504],'Unit','normalized');
colormap(handles.UserData.HiddenFig,handles.Graphics.Colormap);
path=[handles.Path.Results,'Videos\',handles.Data.Date,'\'];
mkdir(path);
handles.UserData.Video = VideoWriter(...
    sprintf('%s%s.mp4',...
    path,[handles.Data.Date,'.',...
    num2str(handles.Data.TS.Time(handles.Data.Edges(handles.Data.j)),...
    '_%07.2f')]));
open(handles.UserData.Video);
handles=SetToolbar(handles);
guidata(hObject,handles);

function Capture_OffCallback(hObject, eventdata, handles)
close(handles.UserData.Video);
delete(handles.UserData.HiddenFig);
handles=SetToolbar(handles);
guidata(hObject,handles);



% --- Creates and returns a handle to the GUI figure. 
function h1 = QuailKit_export_LayoutFcn(policy)
% policy - create a new figure or use a singleton. 'new' or 'reuse'.

persistent hsingleton;
if strcmpi(policy, 'reuse') & ishandle(hsingleton)
    h1 = hsingleton;
    return;
end
load QuailKit_export.mat


appdata = [];
appdata.GUIDEOptions = mat{1};
appdata.lastValidTag = 'Fig';
appdata.GUIDELayoutEditor = [];
appdata.initTags = struct(...
    'handle', [], ...
    'tag', 'Fig');

h1 = figure(...
'PaperUnits',get(0,'defaultfigurePaperUnits'),...
'Units',get(0,'defaultfigureUnits'),...
'Position',[360.333333333333 197.666666666667 960 540],...
'Visible',get(0,'defaultfigureVisible'),...
'Color',[0.941176470588235 0.941176470588235 0.941176470588235],...
'CloseRequestFcn',get(0,'defaultfigureCloseRequestFcn'),...
'CurrentAxesMode','manual',...
'CurrentObjectMode','manual',...
'CurrentPointMode','manual',...
'SelectionTypeMode','manual',...
'ResizeFcn',@(hObject,eventdata)QuailKit('Fig_SizeChangedFcn',hObject,eventdata,guidata(hObject)),...
'IntegerHandle','off',...
'NextPlot',get(0,'defaultfigureNextPlot'),...
'Alphamap',get(0,'defaultfigureAlphamap'),...
'WindowButtonDownFcn',blanks(0),...
'WindowButtonUpFcn',blanks(0),...
'WindowButtonMotionFcn',blanks(0),...
'WindowScrollWheelFcn',blanks(0),...
'WindowKeyPressFcn',blanks(0),...
'WindowKeyReleaseFcn',blanks(0),...
'MenuBar','none',...
'ToolBar',get(0,'defaultfigureToolBar'),...
'Pointer',get(0,'defaultfigurePointer'),...
'PointerShapeHotSpot',get(0,'defaultfigurePointerShapeHotSpot'),...
'Name','Quail Kit (Beta)',...
'NumberTitle','off',...
'HandleVisibility','callback',...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','Fig',...
'UserData',mat{2},...
'WindowStyle',get(0,'defaultfigureWindowStyle'),...
'DockControls',get(0,'defaultfigureDockControls'),...
'Resize',get(0,'defaultfigureResize'),...
'PaperPosition',[-0.75 2.6875 10 5.625],...
'PaperSize',get(0,'defaultfigurePaperSize'),...
'PaperType',get(0,'defaultfigurePaperType'),...
'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
'PaperOrientation',get(0,'defaultfigurePaperOrientation'),...
'ScreenPixelsPerInchMode','manual',...
'KeyPressFcn',@(hObject,eventdata)QuailKit_export('Fig_KeyPressFcn',hObject,eventdata,guidata(hObject)),...
'KeyReleaseFcn',@(hObject,eventdata)QuailKit_export('Fig_KeyReleaseFcn',hObject,eventdata,guidata(hObject)));

appdata = [];
appdata.lastValidTag = 'Toolbar';

h2 = uitoolbar(...
'Parent',h1,...
'Visible',get(0,'defaultuitoolbarVisible'),...
'Interruptible','off',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','Toolbar');

appdata = [];
appdata.toolid = [];
appdata.lastValidTag = 'HT';

h3 = uitoggletool(...
'Parent',h2,...
'Children',[],...
'Interruptible','off',...
'Tag','HT',...
'Tooltip','About',...
'TooltipMode',get(0,'defaultuitoggletoolTooltipMode'),...
'CData',mat{3},...
'ClickedCallback',blanks(0),...
'Separator','on',...
'TooltipString','About',...
'OffCallback',@(hObject,eventdata)QuailKit_export('HT_OffCallback',hObject,eventdata,guidata(hObject)),...
'OnCallback',@(hObject,eventdata)QuailKit_export('HT_OnCallback',hObject,eventdata,guidata(hObject)),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.toolid = [];
appdata.lastValidTag = 'Theme';

h4 = uipushtool(...
'Parent',h2,...
'Children',[],...
'BusyAction','cancel',...
'Interruptible','off',...
'Tag','Theme',...
'UserData',11,...
'Tooltip','Theme',...
'TooltipMode',get(0,'defaultuipushtoolTooltipMode'),...
'CData',mat{4},...
'ClickedCallback',@(hObject,eventdata)QuailKit_export('Theme_ClickedCallback',hObject,eventdata,guidata(hObject)),...
'Enable',get(0,'defaultuipushtoolEnable'),...
'Separator','on',...
'TooltipString','Theme',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.toolid = [];
appdata.lastValidTag = 'InvertColors';

h5 = uitoggletool(...
'Parent',h2,...
'Children',[],...
'Interruptible','off',...
'Tag','InvertColors',...
'Tooltip','Invert Colors',...
'TooltipMode',get(0,'defaultuitoggletoolTooltipMode'),...
'CData',mat{5},...
'ClickedCallback',@(hObject,eventdata)QuailKit_export('InvertColors_ClickedCallback',hObject,eventdata,guidata(hObject)),...
'Separator',get(0,'defaultuitoggletoolSeparator'),...
'TooltipString','Invert Colors',...
'State','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.toolid = [];
appdata.lastValidTag = 'Animation';

h6 = uitoggletool(...
'Parent',h2,...
'Children',[],...
'Tag','Animation',...
'Tooltip','Animation',...
'TooltipMode',get(0,'defaultuitoggletoolTooltipMode'),...
'CData',mat{6},...
'ClickedCallback',@(hObject,eventdata)QuailKit_export('Animation_ClickedCallback',hObject,eventdata,guidata(hObject)),...
'Enable',get(0,'defaultuitoggletoolEnable'),...
'Separator',get(0,'defaultuitoggletoolSeparator'),...
'TooltipString','Animation',...
'OffCallback',blanks(0),...
'OnCallback',blanks(0),...
'State','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.toolid = [];
appdata.lastValidTag = 'Zoom';

h7 = uipushtool(...
'Parent',h2,...
'Children',[],...
'Interruptible','off',...
'Tag','Zoom',...
'Tooltip','Zoom',...
'TooltipMode',get(0,'defaultuipushtoolTooltipMode'),...
'CData',mat{7},...
'ClickedCallback',@(hObject,eventdata)QuailKit_export('Zoom_ClickedCallback',hObject,eventdata,guidata(hObject)),...
'Enable',get(0,'defaultuipushtoolEnable'),...
'Separator',get(0,'defaultuipushtoolSeparator'),...
'TooltipString','Zoom',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.toolid = [];
appdata.lastValidTag = 'Sound';

h8 = uitoggletool(...
'Parent',h2,...
'Children',[],...
'Interruptible','off',...
'Tag','Sound',...
'Tooltip','Sound',...
'TooltipMode',get(0,'defaultuitoggletoolTooltipMode'),...
'CData',mat{8},...
'ClickedCallback',@(hObject,eventdata)QuailKit_export('Sound_ClickedCallback',hObject,eventdata,guidata(hObject)),...
'Separator',get(0,'defaultuitoggletoolSeparator'),...
'TooltipString','Sound',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.toolid = 'Standard.SaveFigure';
appdata.CallbackInUse = struct(...
    'ClickedCallback', 'AudioKit(''Save_ClickedCallback'',gcbo,[],guidata(gcbo))');
appdata.lastValidTag = 'Save';

h9 = uipushtool(...
'Parent',h2,...
'Serializable',get(0,'defaultuipushtoolSerializable'),...
'Children',[],...
'HandleVisibility',get(0,'defaultuipushtoolHandleVisibility'),...
'BusyAction','cancel',...
'Interruptible','off',...
'Tag','Save',...
'Tooltip','Save Figure',...
'TooltipMode',get(0,'defaultuipushtoolTooltipMode'),...
'CData',mat{9},...
'ClickedCallback',@(hObject,eventdata)QuailKit_export('Save_ClickedCallback',hObject,eventdata,guidata(hObject)),...
'Enable',get(0,'defaultuipushtoolEnable'),...
'Separator',get(0,'defaultuipushtoolSeparator'),...
'TooltipString','Save Figure',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.toolid = [];
appdata.lastValidTag = 'Capture';

h10 = uitoggletool(...
'Parent',h2,...
'Children',[],...
'Tag','Capture',...
'Tooltip','Record Figure',...
'TooltipMode',get(0,'defaultuitoggletoolTooltipMode'),...
'CData',mat{10},...
'ClickedCallback',blanks(0),...
'Enable',get(0,'defaultuitoggletoolEnable'),...
'Separator',get(0,'defaultuitoggletoolSeparator'),...
'TooltipString','Record Figure',...
'OffCallback',@(hObject,eventdata)QuailKit_export('Capture_OffCallback',hObject,eventdata,guidata(hObject)),...
'OnCallback',@(hObject,eventdata)QuailKit_export('Capture_OnCallback',hObject,eventdata,guidata(hObject)),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.toolid = [];
appdata.lastValidTag = 'Display';

h11 = uipushtool(...
'Parent',h2,...
'Children',[],...
'Visible','off',...
'Interruptible','off',...
'Tag','Display',...
'Tooltip','Display',...
'TooltipMode',get(0,'defaultuipushtoolTooltipMode'),...
'CData',mat{11},...
'ClickedCallback',@(hObject,eventdata)QuailKit_export('Display_ClickedCallback',hObject,eventdata,guidata(hObject)),...
'Enable',get(0,'defaultuipushtoolEnable'),...
'Separator',get(0,'defaultuipushtoolSeparator'),...
'TooltipString','Display',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Group45';

h12 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units',get(0,'defaultuipanelUnits'),...
'ForegroundColor',get(0,'defaultuipanelForegroundColor'),...
'HighlightColor',get(0,'defaultuipanelHighlightColor'),...
'ShadowColor',get(0,'defaultuipanelShadowColor'),...
'BorderType',get(0,'defaultuipanelBorderType'),...
'BorderWidth',get(0,'defaultuipanelBorderWidth'),...
'TitlePosition',get(0,'defaultuipanelTitlePosition'),...
'Title',blanks(0),...
'Visible',get(0,'defaultuipanelVisible'),...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'ResizeFcn',blanks(0),...
'HandleVisibility',get(0,'defaultuipanelHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','Group45',...
'UserData',[],...
'Position',[0.0104166666666667 0.369135802469136 0.333333333333333 0.296296296296296],...
'FontSize',get(0,'defaultuipanelFontSize'),...
'FontName',get(0,'defaultuipanelFontName'),...
'FontAngle',get(0,'defaultuipanelFontAngle'),...
'FontWeight',get(0,'defaultuipanelFontWeight'));

appdata = [];
appdata.lastValidTag = 'Five';

h13 = uibuttongroup(...
'Parent',h12,...
'FontUnits','points',...
'Units','normalized',...
'SelectionChangeFcn',@(hObject,eventdata)QuailKit('Five_SelectionChangedFcn',get(hObject,'SelectedObject'),eventdata,guidata(get(hObject,'SelectedObject'))),...
'ForegroundColor',[0 0 0],...
'HighlightColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'ShadowColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'BorderType','etchedin',...
'BorderWidth',1,...
'TitlePosition','lefttop',...
'Title',blanks(0),...
'Visible','on',...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'ResizeFcn',blanks(0),...
'HandleVisibility','on',...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','Five',...
'UserData',[],...
'Position',[0.49372635703975 0.0192307692307692 0.504201680672269 1.01694915254237],...
'FontSize',8,...
'FontName','MS Sans Serif',...
'FontAngle','normal',...
'FontWeight','normal');

appdata = [];
appdata.lastValidTag = 'Five_Slide';

h14 = uicontrol(...
'Parent',h13,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',[0.001 0.01],...
'String',blanks(0),...
'Style','slider',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.0254237288135593 0.0254237288135593 0.128746078113167 0.969756738987508],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Callback',@(hObject,eventdata)QuailKit_export('Five_Slide_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','Five_Slide',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'Five_List';

h15 = uicontrol(...
'Parent',h13,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',blanks(0),...
'Style','listbox',...
'Value',1,...
'Position',[0.186681813264092 0.0258601797063336 0.804662988207292 0.775805391190007],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Callback',@(hObject,eventdata)QuailKit_export('Five_List_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',@(hObject,eventdata)QuailKit_export('Five_List_ButtonDownFcn',hObject,eventdata,guidata(hObject)),...
'Interruptible','off',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','Five_List',...
'UserData',mat{12},...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',9,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'Five_Pop';

h16 = uicontrol(...
'Parent',h13,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',{  'Detection Off'; 'Template Matching' },...
'Style','popupmenu',...
'Value',1,...
'Position',[0.184549356223176 0.800865800865801 0.802575107296137 0.194805194805195],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Callback',@(hObject,eventdata)QuailKit_export('Five_Pop_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',[0.149019607843137 0.149019607843137 0.149019607843137],...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','Five_Pop',...
'UserData',0,...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',9,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'Four';

h17 = uibuttongroup(...
'Parent',h12,...
'FontUnits','points',...
'Units','normalized',...
'SelectionChangeFcn',blanks(0),...
'ForegroundColor',[0 0 0],...
'HighlightColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'ShadowColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'BorderType','etchedin',...
'BorderWidth',1,...
'TitlePosition','lefttop',...
'Title',blanks(0),...
'Visible','on',...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'ResizeFcn',blanks(0),...
'HandleVisibility','on',...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','Four',...
'UserData',[],...
'Position',[0.00210970464135021 0.0213675213675214 0.506329113924051 1.02564102564103],...
'FontSize',8,...
'FontName','MS Sans Serif',...
'FontAngle','normal',...
'FontWeight','normal');

appdata = [];
appdata.lastValidTag = 'Four_List';

h18 = uicontrol(...
'Parent',h17,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',blanks(0),...
'Style','listbox',...
'Value',1,...
'Position',[0.185897435897436 0.0256410256410256 0.801282051282051 0.769230769230769],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Callback',@(hObject,eventdata)QuailKit_export('Four_List_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','Four_List',...
'UserData',mat{13},...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',9,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'Four_Slide';

h19 = uicontrol(...
'Parent',h17,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',[0.05 0.1],...
'String',blanks(0),...
'Style','slider',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.0256410256410256 0.0256410256410256 0.128205128205128 0.961538461538461],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Callback',@(hObject,eventdata)QuailKit_export('Four_Slide_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','Four_Slide',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'Four_Pop';

h20 = uicontrol(...
'Parent',h17,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',{  'Visualization Off'; 'Time/Frequency/Correlation' },...
'Style','popupmenu',...
'Value',2,...
'Position',[0.185897435897436 0.794871794871795 0.801282051282051 0.192307692307692],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Callback',@(hObject,eventdata)QuailKit_export('Four_Pop_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',[0.149019607843137 0.149019607843137 0.149019607843137],...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','Four_Pop',...
'UserData',1,...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',9,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'Group123';

h21 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units',get(0,'defaultuipanelUnits'),...
'ForegroundColor',get(0,'defaultuipanelForegroundColor'),...
'HighlightColor',get(0,'defaultuipanelHighlightColor'),...
'ShadowColor',get(0,'defaultuipanelShadowColor'),...
'BorderType',get(0,'defaultuipanelBorderType'),...
'BorderWidth',get(0,'defaultuipanelBorderWidth'),...
'TitlePosition',get(0,'defaultuipanelTitlePosition'),...
'Title',blanks(0),...
'Visible',get(0,'defaultuipanelVisible'),...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'ResizeFcn',blanks(0),...
'HandleVisibility',get(0,'defaultuipanelHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','Group123',...
'UserData',[],...
'Position',[0.0104166666666667 0.680246913580247 0.333333333333333 0.296296296296296],...
'FontSize',get(0,'defaultuipanelFontSize'),...
'FontName',get(0,'defaultuipanelFontName'),...
'FontAngle',get(0,'defaultuipanelFontAngle'),...
'FontWeight',get(0,'defaultuipanelFontWeight'));

appdata = [];
appdata.lastValidTag = 'One';

h22 = uibuttongroup(...
'Parent',h21,...
'FontUnits','points',...
'Units','normalized',...
'SelectionChangeFcn',blanks(0),...
'ForegroundColor',[0 0 0],...
'HighlightColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'ShadowColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'BorderType','etchedin',...
'BorderWidth',1,...
'TitlePosition','lefttop',...
'Title',blanks(0),...
'Visible','on',...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'ResizeFcn',blanks(0),...
'HandleVisibility','on',...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','One',...
'UserData',[],...
'Position',[-5.31858312945429e-05 0.00213675213675214 0.506329113924051 1.02564102564103],...
'FontSize',8,...
'FontName','MS Sans Serif',...
'FontAngle','normal',...
'FontWeight','normal');

appdata = [];
appdata.lastValidTag = 'One_List';

h23 = uicontrol(...
'Parent',h22,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',blanks(0),...
'Style','listbox',...
'Value',1,...
'Position',[0.0253150803998262 0.0334999275677241 0.949315514993481 0.752933507170796],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Callback',@(hObject,eventdata)QuailKit_export('One_List_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','One_List',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',9,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'One_Pop';

h24 = uicontrol(...
'Parent',h22,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',{  'Recording Set'; 'All'; 'Training'; 'Testing' },...
'Style','popupmenu',...
'Value',2,...
'Position',[0.0253150803998262 0.78643343473852 0.949315514993481 0.188233376792699],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Callback',@(hObject,eventdata)QuailKit_export('One_Pop_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','One_Pop',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',9,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'Two';

h25 = uibuttongroup(...
'Parent',h21,...
'FontUnits','points',...
'Units','normalized',...
'SelectionChangeFcn',blanks(0),...
'ForegroundColor',[0 0 0],...
'HighlightColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'ShadowColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'BorderType','etchedin',...
'BorderWidth',1,...
'TitlePosition','lefttop',...
'Title',blanks(0),...
'Visible','on',...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'ResizeFcn',blanks(0),...
'HandleVisibility','on',...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','Two',...
'UserData',[],...
'Position',[0.483122362869198 0.00427350427350427 0.506329113924051 1.02564102564103],...
'FontSize',8,...
'FontName','MS Sans Serif',...
'FontAngle','normal',...
'FontWeight','normal');

appdata = [];
appdata.lastValidTag = 'Two_List';

h26 = uicontrol(...
'Parent',h25,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',blanks(0),...
'Style','listbox',...
'Value',1,...
'Position',[0.185897435897436 0.0256410256410256 0.801282051282051 0.769230769230769],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Callback',@(hObject,eventdata)QuailKit_export('Two_List_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','Two_List',...
'KeyPressFcn',blanks(0),...
'FontSize',9,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'Two_Slide';

h27 = uicontrol(...
'Parent',h25,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',[0.05 0.1],...
'String',blanks(0),...
'Style','slider',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.0256410256410256 0.0256410256410256 0.128205128205128 0.961538461538461],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Callback',@(hObject,eventdata)QuailKit_export('Two_Slide_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','Two_Slide',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'Two_Pop';

h28 = uicontrol(...
'Parent',h25,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',{  'Microphones'; 'Annotations'; 'Info' },...
'Style','popupmenu',...
'Value',1,...
'Position',[0.185897435897436 0.794871794871795 0.801282051282051 0.192307692307692],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Callback',@(hObject,eventdata)QuailKit_export('Two_Pop_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',[0.149019607843137 0.149019607843137 0.149019607843137],...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','Two_Pop',...
'UserData',mat{14},...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',9,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'GroupPlay';

h29 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units',get(0,'defaultuipanelUnits'),...
'ForegroundColor',get(0,'defaultuipanelForegroundColor'),...
'HighlightColor',get(0,'defaultuipanelHighlightColor'),...
'ShadowColor',get(0,'defaultuipanelShadowColor'),...
'BorderType',get(0,'defaultuipanelBorderType'),...
'BorderWidth',get(0,'defaultuipanelBorderWidth'),...
'TitlePosition',get(0,'defaultuipanelTitlePosition'),...
'Title',blanks(0),...
'Visible',get(0,'defaultuipanelVisible'),...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'ResizeFcn',blanks(0),...
'HandleVisibility',get(0,'defaultuipanelHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','GroupPlay',...
'UserData',[],...
'Position',[0.06875 0.0530864197530864 0.208333333333333 0.259259259259259],...
'FontSize',get(0,'defaultuipanelFontSize'),...
'FontName',get(0,'defaultuipanelFontName'),...
'FontAngle',get(0,'defaultuipanelFontAngle'),...
'FontWeight',get(0,'defaultuipanelFontWeight'));

appdata = [];
appdata.lastValidTag = 'Previous';

h30 = uicontrol(...
'Parent',h29,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',blanks(0),...
'Style',get(0,'defaultuicontrolStyle'),...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.197278911564626 0.0490196078431372 0.306122448979592 0.220588235294118],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'CData',mat{15},...
'Callback',@(hObject,eventdata)QuailKit_export('Previous_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','Previous',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'Back';

h31 = uicontrol(...
'Parent',h29,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',blanks(0),...
'Style',get(0,'defaultuicontrolStyle'),...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.197278911564626 0.740196078431373 0.306122448979592 0.220588235294118],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'CData',mat{16},...
'Callback',@(hObject,eventdata)QuailKit_export('Back_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','Back',...
'UserData',0,...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'Clear';

h32 = uicontrol(...
'Parent',h29,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',blanks(0),...
'Style',get(0,'defaultuicontrolStyle'),...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.0204081632653061 0.740196078431373 0.153061224489796 0.220588235294118],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'CData',mat{17},...
'Callback',@(hObject,eventdata)QuailKit_export('Clear_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','Clear',...
'UserData',0,...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight','bold');

appdata = [];
appdata.lastValidTag = 'Reset';

h33 = uicontrol(...
'Parent',h29,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',blanks(0),...
'Style',get(0,'defaultuicontrolStyle'),...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.0204081632653061 0.0490196078431372 0.153061224489796 0.220588235294118],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'CData',mat{18},...
'Callback',@(hObject,eventdata)QuailKit_export('Reset_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',@(hObject,eventdata)Match('Reset_ButtonDownFcn',hObject,eventdata,guidata(hObject)),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','Reset',...
'UserData',0,...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight','bold');

appdata = [];
appdata.lastValidTag = 'Skip';

h34 = uicontrol(...
'Parent',h29,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',blanks(0),...
'Style',get(0,'defaultuicontrolStyle'),...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.503401360544218 0.740196078431373 0.306122448979592 0.220588235294118],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'CData',mat{19},...
'Callback',@(hObject,eventdata)QuailKit_export('Skip_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','Skip',...
'UserData',0,...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'Next';

h35 = uicontrol(...
'Parent',h29,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',blanks(0),...
'Style',get(0,'defaultuicontrolStyle'),...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.503401360544218 0.0490196078431372 0.306122448979592 0.220588235294118],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'CData',mat{20},...
'Callback',@(hObject,eventdata)QuailKit_export('Next_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','Next',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'QueueMode';

h36 = uicontrol(...
'Parent',h29,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',blanks(0),...
'Style','togglebutton',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.826530612244898 0.0490196078431372 0.153061224489796 0.220588235294118],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'CData',mat{21},...
'Callback',@(hObject,eventdata)QuailKit_export('QueueMode_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable','off',...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','QueueMode',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'PlayMode';

h37 = uicontrol(...
'Parent',h29,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',blanks(0),...
'Style',get(0,'defaultuicontrolStyle'),...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.826530612244898 0.740196078431373 0.153061224489796 0.220588235294118],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'CData',mat{22},...
'Callback',@(hObject,eventdata)QuailKit_export('PlayMode_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','PlayMode',...
'UserData',0,...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'Mode';

h38 = uicontrol(...
'Parent',h29,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',blanks(0),...
'Style',get(0,'defaultuicontrolStyle'),...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.0204081632653061 0.284313725490196 0.153061224489796 0.441176470588235],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'CData',mat{23},...
'Callback',@(hObject,eventdata)QuailKit_export('Mode_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','Mode',...
'UserData',0,...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'Debug';

h39 = uicontrol(...
'Parent',h29,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',blanks(0),...
'Style',get(0,'defaultuicontrolStyle'),...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.826530612244898 0.284313725490196 0.153061224489796 0.441176470588235],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'CData',mat{24},...
'Callback',@(hObject,eventdata)QuailKit_export('Debug_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable','off',...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','Debug',...
'UserData',0,...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight','bold');

appdata = [];
appdata.lastValidTag = 'Play';

h40 = uicontrol(...
'Parent',h29,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',blanks(0),...
'Style',get(0,'defaultuicontrolStyle'),...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.197278911564626 0.284313725490196 0.612244897959184 0.441176470588235],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'CData',mat{25},...
'Callback',@(hObject,eventdata)QuailKit_export('Play_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','Play',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'Panel';

h41 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units',get(0,'defaultuipanelUnits'),...
'ForegroundColor',[0.96078431372549 0.96078431372549 0.96078431372549],...
'HighlightColor',[0.96078431372549 0.96078431372549 0.96078431372549],...
'ShadowColor',[0.501960784313725 0.501960784313725 0.501960784313725],...
'BorderType',get(0,'defaultuipanelBorderType'),...
'BorderWidth',get(0,'defaultuipanelBorderWidth'),...
'TitlePosition',get(0,'defaultuipanelTitlePosition'),...
'Title',blanks(0),...
'Visible',get(0,'defaultuipanelVisible'),...
'BackgroundColor',[0.96078431372549 0.96078431372549 0.96078431372549],...
'ResizeFcn',blanks(0),...
'HandleVisibility',get(0,'defaultuipanelHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','Panel',...
'UserData',[],...
'Position',[0.358333333333333 0.0740740740740741 0.626388888888889 0.882716049382716],...
'FontSize',get(0,'defaultuipanelFontSize'),...
'FontName',get(0,'defaultuipanelFontName'),...
'FontAngle',get(0,'defaultuipanelFontAngle'),...
'FontWeight',get(0,'defaultuipanelFontWeight'));


hsingleton = h1;


% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   if isa(createfcn,'function_handle')
       createfcn(hObject, eventdata);
   else
       eval(createfcn);
   end
end


% --- Handles default GUIDE GUI creation and callback dispatch
function varargout = gui_mainfcn(gui_State, varargin)

gui_StateFields =  {'gui_Name'
    'gui_Singleton'
    'gui_OpeningFcn'
    'gui_OutputFcn'
    'gui_LayoutFcn'
    'gui_Callback'};
gui_Mfile = '';
for i=1:length(gui_StateFields)
    if ~isfield(gui_State, gui_StateFields{i})
        error(message('MATLAB:guide:StateFieldNotFound', gui_StateFields{ i }, gui_Mfile));
    elseif isequal(gui_StateFields{i}, 'gui_Name')
        gui_Mfile = [gui_State.(gui_StateFields{i}), '.m'];
    end
end

numargin = length(varargin);

if numargin == 0
    % QUAILKIT_EXPORT
    % create the GUI only if we are not in the process of loading it
    % already
    gui_Create = true;
elseif local_isInvokeActiveXCallback(gui_State, varargin{:})
    % QUAILKIT_EXPORT(ACTIVEX,...)
    vin{1} = gui_State.gui_Name;
    vin{2} = [get(varargin{1}.Peer, 'Tag'), '_', varargin{end}];
    vin{3} = varargin{1};
    vin{4} = varargin{end-1};
    vin{5} = guidata(varargin{1}.Peer);
    feval(vin{:});
    return;
elseif local_isInvokeHGCallback(gui_State, varargin{:})
    % QUAILKIT_EXPORT('CALLBACK',hObject,eventData,handles,...)
    gui_Create = false;
else
    % QUAILKIT_EXPORT(...)
    % create the GUI and hand varargin to the openingfcn
    gui_Create = true;
end

if ~gui_Create
    % In design time, we need to mark all components possibly created in
    % the coming callback evaluation as non-serializable. This way, they
    % will not be brought into GUIDE and not be saved in the figure file
    % when running/saving the GUI from GUIDE.
    designEval = false;
    if (numargin>1 && ishghandle(varargin{2}))
        fig = varargin{2};
        while ~isempty(fig) && ~ishghandle(fig,'figure')
            fig = get(fig,'parent');
        end
        
        designEval = isappdata(0,'CreatingGUIDEFigure') || (isscalar(fig)&&isprop(fig,'GUIDEFigure'));
    end
        
    if designEval
        beforeChildren = findall(fig);
    end
    
    % evaluate the callback now
    varargin{1} = gui_State.gui_Callback;
    if nargout
        [varargout{1:nargout}] = feval(varargin{:});
    else       
        feval(varargin{:});
    end
    
    % Set serializable of objects created in the above callback to off in
    % design time. Need to check whether figure handle is still valid in
    % case the figure is deleted during the callback dispatching.
    if designEval && ishghandle(fig)
        set(setdiff(findall(fig),beforeChildren), 'Serializable','off');
    end
else
    if gui_State.gui_Singleton
        gui_SingletonOpt = 'reuse';
    else
        gui_SingletonOpt = 'new';
    end

    % Check user passing 'visible' P/V pair first so that its value can be
    % used by oepnfig to prevent flickering
    gui_Visible = 'auto';
    gui_VisibleInput = '';
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        % Recognize 'visible' P/V pair
        len1 = min(length('visible'),length(varargin{index}));
        len2 = min(length('off'),length(varargin{index+1}));
        if ischar(varargin{index+1}) && strncmpi(varargin{index},'visible',len1) && len2 > 1
            if strncmpi(varargin{index+1},'off',len2)
                gui_Visible = 'invisible';
                gui_VisibleInput = 'off';
            elseif strncmpi(varargin{index+1},'on',len2)
                gui_Visible = 'visible';
                gui_VisibleInput = 'on';
            end
        end
    end
    
    % Open fig file with stored settings.  Note: This executes all component
    % specific CreateFunctions with an empty HANDLES structure.

    
    % Do feval on layout code in m-file if it exists
    gui_Exported = ~isempty(gui_State.gui_LayoutFcn);
    % this application data is used to indicate the running mode of a GUIDE
    % GUI to distinguish it from the design mode of the GUI in GUIDE. it is
    % only used by actxproxy at this time.   
    setappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]),1);
    if gui_Exported
        gui_hFigure = feval(gui_State.gui_LayoutFcn, gui_SingletonOpt);

        % make figure invisible here so that the visibility of figure is
        % consistent in OpeningFcn in the exported GUI case
        if isempty(gui_VisibleInput)
            gui_VisibleInput = get(gui_hFigure,'Visible');
        end
        set(gui_hFigure,'Visible','off')

        % openfig (called by local_openfig below) does this for guis without
        % the LayoutFcn. Be sure to do it here so guis show up on screen.
        movegui(gui_hFigure,'onscreen');
    else
        gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        % If the figure has InGUIInitialization it was not completely created
        % on the last pass.  Delete this handle and try again.
        if isappdata(gui_hFigure, 'InGUIInitialization')
            delete(gui_hFigure);
            gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        end
    end
    if isappdata(0, genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]))
        rmappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]));
    end

    % Set flag to indicate starting GUI initialization
    setappdata(gui_hFigure,'InGUIInitialization',1);

    % Fetch GUIDE Application options
    gui_Options = getappdata(gui_hFigure,'GUIDEOptions');
    % Singleton setting in the GUI MATLAB code file takes priority if different
    gui_Options.singleton = gui_State.gui_Singleton;

    if ~isappdata(gui_hFigure,'GUIOnScreen')
        % Adjust background color
        if gui_Options.syscolorfig
            set(gui_hFigure,'Color', get(0,'DefaultUicontrolBackgroundColor'));
        end

        % Generate HANDLES structure and store with GUIDATA. If there is
        % user set GUI data already, keep that also.
        data = guidata(gui_hFigure);
        handles = guihandles(gui_hFigure);
        if ~isempty(handles)
            if isempty(data)
                data = handles;
            else
                names = fieldnames(handles);
                for k=1:length(names)
                    data.(char(names(k)))=handles.(char(names(k)));
                end
            end
        end
        guidata(gui_hFigure, data);
    end

    % Apply input P/V pairs other than 'visible'
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        len1 = min(length('visible'),length(varargin{index}));
        if ~strncmpi(varargin{index},'visible',len1)
            try set(gui_hFigure, varargin{index}, varargin{index+1}), catch break, end
        end
    end

    % If handle visibility is set to 'callback', turn it on until finished
    % with OpeningFcn
    gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
    if strcmp(gui_HandleVisibility, 'callback')
        set(gui_hFigure,'HandleVisibility', 'on');
    end

    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        % Handle the default callbacks of predefined toolbar tools in this
        % GUI, if any
        guidemfile('restoreToolbarToolPredefinedCallback',gui_hFigure); 
        
        % Update handle visibility
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);

        % Call openfig again to pick up the saved visibility or apply the
        % one passed in from the P/V pairs
        if ~gui_Exported
            gui_hFigure = local_openfig(gui_State.gui_Name, 'reuse',gui_Visible);
        elseif ~isempty(gui_VisibleInput)
            set(gui_hFigure,'Visible',gui_VisibleInput);
        end
        if strcmpi(get(gui_hFigure, 'Visible'), 'on')
            figure(gui_hFigure);
            
            if gui_Options.singleton
                setappdata(gui_hFigure,'GUIOnScreen', 1);
            end
        end

        % Done with GUI initialization
        if isappdata(gui_hFigure,'InGUIInitialization')
            rmappdata(gui_hFigure,'InGUIInitialization');
        end

        % If handle visibility is set to 'callback', turn it on until
        % finished with OutputFcn
        gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
        if strcmp(gui_HandleVisibility, 'callback')
            set(gui_hFigure,'HandleVisibility', 'on');
        end
        gui_Handles = guidata(gui_hFigure);
    else
        gui_Handles = [];
    end

    if nargout
        [varargout{1:nargout}] = feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    else
        feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    end

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);
    end
end

function gui_hFigure = local_openfig(name, singleton, visible)

% openfig with three arguments was new from R13. Try to call that first, if
% failed, try the old openfig.
if nargin('openfig') == 2
    % OPENFIG did not accept 3rd input argument until R13,
    % toggle default figure visible to prevent the figure
    % from showing up too soon.
    gui_OldDefaultVisible = get(0,'defaultFigureVisible');
    set(0,'defaultFigureVisible','off');
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton);
    set(0,'defaultFigureVisible',gui_OldDefaultVisible);
else
    % Call version of openfig that accepts 'auto' option"
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton, visible);  
%     %workaround for CreateFcn not called to create ActiveX
%         peers=findobj(findall(allchild(gui_hFigure)),'type','uicontrol','style','text');    
%         for i=1:length(peers)
%             if isappdata(peers(i),'Control')
%                 actxproxy(peers(i));
%             end            
%         end
end

function result = local_isInvokeActiveXCallback(gui_State, varargin)

try
    result = ispc && iscom(varargin{1}) ...
             && isequal(varargin{1},gcbo);
catch
    result = false;
end

function result = local_isInvokeHGCallback(gui_State, varargin)

try
    fhandle = functions(gui_State.gui_Callback);
    result = ~isempty(findstr(gui_State.gui_Name,fhandle.file)) || ...
             (ischar(varargin{1}) ...
             && isequal(ishghandle(varargin{2}), 1) ...
             && (~isempty(strfind(varargin{1},[get(varargin{2}, 'Tag'), '_'])) || ...
                ~isempty(strfind(varargin{1}, '_CreateFcn'))) );
catch
    result = false;
end


