% Compute power spectrum

% Generated by MATLAB(R) 9.5 and Signal Processing Toolbox 8.1.
% Generated on: 29-Mar-2019 20:54:47

% Parameters
frequencyLimits = [0 1]; % Normalized frequency (*pi rad/sample)

%%
% Index into signal time region of interest
figure()
timeLimits = [1 51888]; % samples
s1_ROI = s1(:);
s1_ROI = s1_ROI(timeLimits(1):timeLimits(2));

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[Ps1_ROI, Fs1_ROI] = pspectrum(s1_ROI, ...
    'FrequencyLimits',frequencyLimits);

%%
% Index into signal time region of interest
timeLimits = [1 51888]; % samples
s2_ROI = s2(:);
s2_ROI = s2_ROI(timeLimits(1):timeLimits(2));

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[Ps2_ROI, Fs2_ROI] = pspectrum(s2_ROI, ...
    'FrequencyLimits',frequencyLimits);
